-- 20260707_000020_referral_slip_number_hotfix.sql
-- OCHP hotfix: generate referral slip numbers inside create_referral_secure().

CREATE OR REPLACE FUNCTION next_referral_slip_no()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  current_year text := to_char(current_date, 'YYYY');
  next_number integer;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext('referrals.slip_no.' || current_year));

  SELECT coalesce(max(substring(slip_no from 11 for 6)::integer), 0) + 1
  INTO next_number
  FROM referrals
  WHERE slip_no ~ ('^OHGL-' || current_year || '-[0-9]{6}$');

  RETURN 'OHGL-' || current_year || '-' || lpad(next_number::text, 6, '0');
END;
$;
REVOKE EXECUTE ON FUNCTION next_referral_slip_no() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION next_referral_slip_no() FROM authenticated;

CREATE OR REPLACE FUNCTION create_referral_secure(payload jsonb)
RETURNS referrals
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  rec referrals;
  patient_rec patients;
  fid uuid;
  dept_id uuid;
  dept_name text;
  encrypt_key text := current_setting('app.encryption_key', true);
  normalized_nid text := regexp_replace(coalesce(payload->>'national_id', ''), '\D', '', 'g');
  start_status referral_canonical_status := coalesce(nullif(payload->>'referral_status', '')::referral_canonical_status, 'submitted'::referral_canonical_status);
  start_stage referral_stage;
BEGIN
  IF jsonb_exists(payload, 'slip_no') THEN
    RAISE EXCEPTION 'Referral slip number is generated by the database and must not be supplied.';
  END IF;

  PERFORM validate_referral_permission('referral:create');

  IF start_status NOT IN ('draft', 'submitted') THEN
    RAISE EXCEPTION 'New referrals must start as draft or submitted.';
  END IF;

  fid := coalesce(
    nullif(payload->>'referral_facility_id', '')::uuid,
    nullif(payload->>'facility_id', '')::uuid,
    public.current_user_facility()
  );
  dept_id := nullif(payload->>'department_id', '')::uuid;

  PERFORM validate_referral_facility(fid);
  PERFORM validate_referral_department(dept_id, fid);

  IF NOT (public.current_user_role() = 'super_admin'::app_role OR public.same_facility(fid)) THEN
    RAISE EXCEPTION 'Wrong facility for referral creation.';
  END IF;

  IF nullif(trim(coalesce(payload->>'patient_name', '')), '') IS NULL THEN
    RAISE EXCEPTION 'Patient name is required.';
  END IF;

  IF start_status = 'submitted' AND (normalized_nid = '' OR normalized_nid !~ '^[0-9]{6,12}$') THEN
    RAISE EXCEPTION 'Valid National ID is required before submission.';
  END IF;

  IF normalized_nid <> '' AND EXISTS (
    SELECT 1
    FROM referrals
    WHERE national_id = normalized_nid
      AND referral_status NOT IN ('completed', 'closed', 'cancelled', 'archived')
  ) THEN
    RAISE EXCEPTION 'An active referral already exists for this patient identifier.';
  END IF;

  SELECT department_name INTO dept_name
  FROM departments
  WHERE id = dept_id;

  INSERT INTO patients (
    facility_id,
    full_name,
    national_id,
    phone,
    sex,
    created_by
  ) VALUES (
    fid,
    trim(payload->>'patient_name'),
    NULLIF(normalized_nid, ''),
    NULLIF(payload->>'phone', ''),
    NULLIF(payload->>'sex', ''),
    auth.uid()
  )
  RETURNING * INTO patient_rec;

  start_stage := public.referral_stage_for_status(start_status);

  INSERT INTO referrals (
    facility_id,
    patient_id,
    slip_no,
    referral_date,
    chp_code,
    chp_unit,
    patient_name_ciphertext,
    national_id,
    phone,
    age,
    sex,
    county,
    subcounty,
    village,
    category,
    priority,
    sha_registered,
    presenting_concern_ciphertext,
    referral_reason,
    clinical_notes_ciphertext,
    referral_facility_id,
    referral_facility_name,
    department,
    department_id,
    opd_status,
    referral_status,
    referral_stage,
    referral_outcome,
    current_owner_type,
    current_owner_facility_id,
    current_owner_department,
    created_by,
    updated_by
  ) VALUES (
    fid,
    patient_rec.id,
    public.next_referral_slip_no(),
    coalesce(nullif(payload->>'referral_date', '')::date, current_date),
    NULLIF(payload->>'chp_code', ''),
    NULLIF(payload->>'chp_unit', ''),
    pgp_sym_encrypt(coalesce(payload->>'patient_name', ''), encrypt_key),
    NULLIF(normalized_nid, ''),
    NULLIF(payload->>'phone', ''),
    NULLIF(payload->>'age', '')::int,
    NULLIF(payload->>'sex', ''),
    NULLIF(payload->>'county', ''),
    NULLIF(payload->>'subcounty', ''),
    NULLIF(payload->>'village', ''),
    CASE WHEN nullif(coalesce(dept_name, payload->>'department'), '') IS NULL THEN '{}'::text[] ELSE ARRAY[coalesce(dept_name, payload->>'department')] END,
    coalesce(nullif(payload->>'priority', '')::referral_priority, 'Routine'::referral_priority),
    coalesce(nullif(payload->>'sha_registered', '')::boolean, false),
    pgp_sym_encrypt(coalesce(payload->>'presenting_concern', ''), encrypt_key),
    NULLIF(payload->>'referral_reason', ''),
    pgp_sym_encrypt(coalesce(payload->>'clinical_notes', ''), encrypt_key),
    fid,
    NULLIF(payload->>'referral_facility_name', ''),
    coalesce(dept_name, NULLIF(payload->>'department', '')),
    dept_id,
    public.referral_legacy_opd_status(start_status),
    start_status,
    start_stage,
    'unknown'::referral_outcome,
    'facility'::referral_owner_type,
    fid,
    coalesce(dept_name, NULLIF(payload->>'department', '')),
    auth.uid(),
    auth.uid()
  )
  RETURNING * INTO rec;

  PERFORM write_referral_event(rec.id, 'create_referral', NULL, rec.referral_status, NULL, rec.referral_stage, rec.current_owner_type, rec.current_owner_user_id, rec.current_owner_facility_id, rec.current_owner_department, rec.facility_id, NULL, payload, 'workflow', false);
  PERFORM write_referral_audit(rec.id, 'create_referral', rec.facility_id, '{}'::jsonb, jsonb_build_object('status', rec.referral_status, 'stage', rec.referral_stage, 'slip_no', rec.slip_no), NULL);
  PERFORM update_referral_sla(rec.id, 'create_referral');
  PERFORM queue_notification_event(rec.id, 'create_referral', rec.facility_id, payload);

  RETURN rec;
END;
$$;

GRANT EXECUTE ON FUNCTION create_referral_secure(jsonb) TO authenticated;